export const ADD_LAND_OWNER = 'ADD_LAND_OWNER';
export const FETCH_LAND_OWNERS = 'FETCH_LAND_OWNERS';
export const UPDATE_LANDOWNER_STATUS= 'UPDATE_LANDOWNER_STATUS';
export const EDIT_OWNER= 'EDIT_OWNER';
