export const ADD_OPERATOR = 'ADD_OPERATOR';
export const FETCH_OPERATOR = 'FETCH_OPERATOR';
export const ADD_CROP = 'ADD_CROP';
export const FETCH_CROPS = 'FETCH_CROPS';
export const EDIT_CROP = 'EDIT_CROP';
export const ADD_LANDPARCEL = 'ADD_LANDPARCEL';
export const FETCH_LANDPARCEL = 'FETCH_LANDPARCEL';
export const EDIT_LANDPARCEL = 'EDIT_LANDPARCEL';
export const UPDATE_OPERATOR_STATUS = 'UPDATE_OPERATOR_STATUS';
export const EDIT_OPERATOR = 'EDIT_OPERATOR';

