export const FETCH_LAND_PARCELS = 'FETCH_LAND_PARCELS';
export const ADD_LAND_PARCEL = 'ADD_LAND_PARCEL';
export const EDIT_PARCEL = 'EDIT_PARCEL';
export const UPDATE_LANDPARCEL_STATUS = 'UPDATE_LANDPARCEL_STATUS';
